// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuGOf6PnR-xonlNpZivDLWPUQDCALGw8E',
    appId: '1:900812141361:web:001df2914c1c3a22c27610',
    messagingSenderId: '900812141361',
    projectId: 'little-house-clothing-catalog',
    authDomain: 'little-house-clothing-catalog.firebaseapp.com',
    storageBucket: 'little-house-clothing-catalog.firebasestorage.app',
    measurementId: 'G-XVP5GXPE88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbMcdLd3BcXhRK7D1bg01YPldNriEPOL0',
    appId: '1:900812141361:android:5e9dfdb06998a090c27610',
    messagingSenderId: '900812141361',
    projectId: 'little-house-clothing-catalog',
    storageBucket: 'little-house-clothing-catalog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI-RqoYv-NmWSJ85u0TRKXk2Kl17W-348',
    appId: '1:900812141361:ios:0645edee35168e08c27610',
    messagingSenderId: '900812141361',
    projectId: 'little-house-clothing-catalog',
    storageBucket: 'little-house-clothing-catalog.firebasestorage.app',
    iosBundleId: 'com.example.littleHouseClothingCatalog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI-RqoYv-NmWSJ85u0TRKXk2Kl17W-348',
    appId: '1:900812141361:ios:0645edee35168e08c27610',
    messagingSenderId: '900812141361',
    projectId: 'little-house-clothing-catalog',
    storageBucket: 'little-house-clothing-catalog.firebasestorage.app',
    iosBundleId: 'com.example.littleHouseClothingCatalog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuGOf6PnR-xonlNpZivDLWPUQDCALGw8E',
    appId: '1:900812141361:web:320fb71a63060b27c27610',
    messagingSenderId: '900812141361',
    projectId: 'little-house-clothing-catalog',
    authDomain: 'little-house-clothing-catalog.firebaseapp.com',
    storageBucket: 'little-house-clothing-catalog.firebasestorage.app',
    measurementId: 'G-S6E60EYNHM',
  );
}
